.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2014 Giuseppe Lavagetto <glavagetto@wikimedia.org>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH QUICKSTACK 1 "October 20, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
quickstack \- tool to take call stack traces with minimal overheads.
.SH SYNOPSIS
.B quickstack
.RI -p PID
.SH DESCRIPTION
This manual page documents briefly the
.B There are a couple of tools to take stack traces such as gdb, pstack, but these tools
have serious overheads. In many cases, target process stops for 0.2-N seconds.
So it is dangerous to use such tools in production environment.
quickstack makes it possible to take stack traces in less than 1 milliseconds. This is
much smaller overhead so you can frequently take stack traces in production environment.
.
.SH "OPTIONS"
There are not many options to specify
.TP
.B \-p PID,
Specify the PID to take the stack trace of.
